#!/usr/bin/python3
import sys
import math

def is_prime(number):
    if number < 2:
        return False
    for i in range(2, int(math.sqrt(number)) + 1):
        if number % i == 0:
            return False
    return True

def factorize_rsa_number(n):
    factors = []
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0 and is prime(i) and is_prime(n // i):
             factors.append((i, n // i))
        return factors

def factorize_rsa_numbers_from_file(file_name):
    try:
        with open(file_name, 'r') as file:
            number = int(file.readline().strip())
            factorizations = factorize_rsa_number(number)
            for p, q in factorizations:
                print(f"n = {p} * {q}")
    except FileNotFoundError:
        print("File not found.")
    except ValueError:
        print("Invalid number in the file.")
    except Exception as e:
        print(f"An error occurred: {str(e)}")
    

    if __name__ == "__main__":
        if len(sys.argv) < 2:
            print("Usage: rsa_factors <file>")
        else:
            file_name = sys.argv[1]
            factorize_rsa_numbers_from_file(file_name)
